### ISSUE TITLE
srcdeps.failOnGoals

### ISSUE THREAD

**Issue by jpkrohling** [l2x6/srcdeps-maven-plugin#37]
The old src-deps fails when the profile "release" is activated, but that's already too late in the process, as the commits were made already. Best would be to have srcdeps to fail early. For that, the best approach is by implementing a `srcdeps.failOnGoals`, with the `release:prepare` and `release:perform` as the default set of values.

**Comment by ppalaga** [comment]
Some basic hints for the implementation:

You'd probably would have to hook somewhere around here https://github.com/l2x6/srcdeps/blob/master/srcdeps-maven-local-repository/src/main/java/org/l2x6/srcdeps/localrepo/SrcdepsLocalRepositoryManager.java#L196 after `if (!config.isSkip()) {`

You'd have to get the session like this `MavenSession mavenSession = sessionProvider.get();` https://github.com/l2x6/srcdeps/blob/master/srcdeps-maven-local-repository/src/main/java/org/l2x6/srcdeps/localrepo/SrcdepsLocalRepositoryManager.java#L125 and the Session should contain the goals somewhere, probably in `mavenSession.getRequest()`.

Goals are Maven specific and the question is if we want to pollute `org.l2x6.srcdeps.core.config.Configuration` with a Maven specific field. It would be great if you could come up with a better solution.

**Comment by ppalaga** [comment]
Also note that there is an unofficial https://github.com/ppalaga/srcdeps-maven-local-repository-quickstart that I use for manual testing.

**Comment by ppalaga** [comment]
The configuration option goes to core: https://github.com/srcdeps/srcdeps-core/pull/2

**Comment by ppalaga** [comment]
https://github.com/srcdeps/srcdeps-core/pull/2 is now merged and this issue is thus fixed.
